hub:
   image:
      name: jupyterhub/k8s-hub
      tag: ve9661be
   db:
     pvc:
       # HACK! I can't create anything not under students tho
       subPath: students/hubdb
       selector:
         matchLabels:
           type: nfs
           kind: hubdb
       accessModes:
         - ReadWriteMany

ingress:
  enabled: true
  host: data8.haas.berkeley.edu
  https:
    enabled: true
    type: "kube-lego"
  annotations:
    kubernetes.io/ingress.class: nginx


proxy:
  service:
    type: ClusterIP
  image:
     name: jupyterhub/k8s-proxy
     tag: v0.3.1
  cmd: null


singleuser:
   storage:
     type: static
     static:
         pvcName: data8-nfs
         subPath: "students/{username}"
   image:
     name: berkeleydsep/singleuser-data8
     tag: e306f80
   extraEnv:
     ALLOWED_GITHUB_ACCOUNTS: "data-8:ds-modules"

auth:
  type: google

admin:
  users:
    # infrastructure
    - 'rylo'
    - 'yuvipanda'
    - 'gunjan_baid'
    - 'peterkangveerman'
    # instructor
    - 'henrym'
    - 'samlau95'
