hub:
   image:
      name: jupyterhub/k8s-hub
      tag: v7b0838e
   db:
     type: sqlite-memory

ingress:
  enabled: true
  host: data8.haas.berkeley.edu
  https:
    enabled: true
    type: "kube-lego"
  annotations:
    kubernetes.io/ingress.class: nginx


proxy:
  service:
    type: ClusterIP

singleuser:
   storage:
     type: static
     static:
         pvcName: data8-nfs
         subPath: "students/{username}"
   image:
     name: berkeleydsep/singleuser-data8
     tag: f20d39a

auth:
  type: google

admin:
  users:
    # infrastructure
    - 'rylo'
    - 'yuvipanda'
    - 'gunjan_baid'
    # instructor
    - 'henrym'
    - 'samlau95'
