hub:
   image:
      name: jupyterhub/k8s-hub
      tag: ve9661be 
   db:
     type: sqlite-pvc
     pvc:
       # HACK! I can't create anything not under students tho
       selector:
         matchLabels:
           type: nfs
           kind: hubdb
           class: data8r
       accessModes:
         - ReadWriteMany


ingress:
  enabled: true
  host: data8r.datahub.berkeley.edu
  https:
    enabled: true
    type: "kube-lego"
  annotations:
    kubernetes.io/ingress.class: nginx


proxy:
  service:
    type: ClusterIP

singleuser:
   storage:
     type: static
     static:
         pvcName: data8r-nfs
         subPath: "students/{username}"
   image:
     name: berkeleydsep/singleuser-data8
     tag: f20d39a
   extraEnv:
     ALLOWED_GITHUB_ACCOUNTS: "data-8:data-8r"

auth:
  type: google

admin:
  users:
    # infrastructure
    - 'rylo'
    - 'yuvipanda'
    - 'gunjan_baid'
    - 'peterkangveerman'
    # instructor
    - 'henrym'
    - 'samlau95'
