hub:
   image:
      name: jupyterhub/k8s-hub
      tag: v7b0838e
   db:
     type: postgres

ingress:
  enabled: true
  host: hub.data8r.omgwtf.in
  https:
    enabled: true
    type: "kube-lego"
  annotations:
    kubernetes.io/ingress.class: nginx


proxy:
  service:
    type: ClusterIP

singleuser:
   storage:
     type: static
     static:
         pvcName: nfs
         subPath: "students/{username}"
   image:
     name: berkeleydsep/singleuser-data8
     tag: v0.2

auth:
  type: google
