apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi # doesn't actually matter
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.7
    path: "/export/homes/data8r/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  selector:
    matchLabels:
      type: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # doesn't actually matter
