hub:
   image:
      name: jupyterhub/k8s-hub
      tag: ve9661be
   db:
     pvc:
       # HACK! I can't create anything not under students tho
       subPath: students/PHY151/hubdb
       selector:
         matchLabels:
           type: nfs
           kind: hubdb
       accessModes:
         - ReadWriteMany

ingress:
  enabled: true
  host: phy151.haas.berkeley.edu
  https:
    enabled: true
    type: "kube-lego"
  annotations:
    kubernetes.io/ingress.class: nginx


proxy:
  service:
    type: ClusterIP
  image:
     name: jupyterhub/k8s-proxy
     tag: v0.3.1
  cmd: null


singleuser:
   storage:
     type: static
     static:
         pvcName: phy151-nfs
         subPath: "students/PHY151/{username}"
   image:
     name: berkeleydsep/singleuser-data8
     tag: f20d39a

auth:
  type: google

admin:
  users:
    # infrastructure
    - 'rylo'
    - 'yuvipanda'
